# Jekyll site
# Package your Jekyll site using the jekyll/builder Docker container image.
# Add steps that build, test, save build artifacts, deploy, and more:
# https://aka.ms/yaml

trigger:
- will-jekyll-template

stages:
- stage: BuildPoanchenPersonalWebsite
  jobs:
  - job: UseRuby
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseRubyVersion@0
      displayName: Use Ruby >= 2.4
    
    - script: 'gem install jekyll'
      displayName: Install Jekyll
      
    - script: 'gem install jekyll-sitemap'
      displayName: Install jekyll-sitemap

    - script: 'jekyll build'
      displayName: Build Jekyll project
      
    - task: CopyFiles@2
      displayName: Copy "_site" to staging directory
      inputs:
        SourceFolder: '_site'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: _site'
      inputs:
        ArtifactName: '_site'
